Function/building
IkumaUchida/trajectory_retrieval pull request #6
Opened 2022-07-06 05:51 UTC by IkumaUchida

2022-07-06 06:57 UTC, AtomScott requested changes

2022-07-06 06:57 UTC, AtomScott commented on .gitignore
> +data/*
dataとSoccerDataが混在するとどっちを使えばいいか明示的ではないとので片方にしたほうがいいね。

2022-07-06 06:57 UTC, AtomScott commented on tasc_retrieval/building.py
> +class Classifier(BaseEstimator, ClassifierMixin):
もっと意味のある（動作が推測可能な）クラス名にした方が分かりやすい。
scitkit-learnにある`sklearn.cluster.AffinityPropagation`, `sklearn.cluster. KMeans`あたりが参考になると思う。

2022-07-06 06:57 UTC, AtomScott commented on tasc_retrieval/building.py
> +class Classifier(BaseEstimator, ClassifierMixin):
[ClassifierMixin](https://github.com/scikit-learn/scikit-learn/blob/baf0ea25d6dd034403370fea552b21a6776bef18/sklearn/base.py#L635)を使うことで、

* `score()`が追加される。
* `{"requires_y": True}`が設定される。

正解ラベルが必要あればこれで間違いないけど、、どう？

* [TransformerMixin](https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html)
* [ClusterMixin](https://scikit-learn.org/stable/modules/generated/sklearn.base.ClusterMixin.html)

を使うかどうか

2022-07-06 06:57 UTC, AtomScott commented on tasc_retrieval/building.py
> +    def __init__(self,
https://scikit-learn.org/dev/developers/develop.html#instantiation にはこう書かれているので、合わせよう。

> This concerns the creation of an object. The object’s __init__ method might accept constants as arguments that determine the estimator’s behavior (like the C constant in SVMs). It should not, however, take the actual training data as an argument, as this is left to the fit() method:
> 
> ```
> clf2 = SVC(C=2.3)
> clf3 = SVC([[1, 2], [2, 3]], [-1, 1]) # WRONG!
> 
> ```
> ...
>To summarize, an __init__ should look like:
> ```python
> def __init__(self, param1=1, param2=2):
>     self.param1 = param1
>     self.param2 = param2
> ```
> There should be no logic, not even input validation, and the parameters should not be changed. The corresponding logic should be put where the parameters are used, typically in fit. The following is wrong:
> ```python
> def __init__(self, param1=1, param2=2, param3=3):
>     # WRONG: parameters should not be modified
>     if param1 > 1:
>         param2 += 1
>     self.param1 = param1
>     # WRONG: the object's attributes should have exactly the name of
>     # the argument in the constructor
>     self.param3 = param2
> ```

学習データはパラメータじゃないので注意

2022-07-06 06:57 UTC, AtomScott commented on tasc_retrieval/building.py
> +        if solver == 'Jaccard':
`self.solver`に書き換えて、引数を消す。

2022-07-07 01:19 UTC, AtomScott requested changes
追加で`transform()`があると新しいデータ（セグメント行列）が入ってきた時に変換できるようになるので、[scikit-learnのPCA](https://github.com/scikit-learn/scikit-learn/blob/baf0ea25d6dd034403370fea552b21a6776bef18/sklearn/decomposition/_base.py#L100)を参考に実装するとよさそう。

このままでも多分pipelineに組み込めるのでほぼOK！

2022-07-07 01:19 UTC, AtomScott commented on tasc_retrieval/building.py
> +    def _calc_simirality_index(self, A, B):
ここはGood

2022-07-07 01:19 UTC, AtomScott commented on tasc_retrieval/building.py
> +        corpus(dict) : Data of dictionary type with tokens stored
ここでリターンするのは`self`なんじゃない？TSNEのドキュメントも間違ってる気がする。

2022-07-08 01:00 UTC, IkumaUchida commented
一旦developmentブランチにマージします

2022-07-08 01:01 UTC, merged